services:
  api:
    container_name: linkpecas_api
    build: .
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    depends_on:
      - db
      - redis
      - meilisearch

  db:
    image: postgres:16
    container_name: linkpecas_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: linkpecas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: linkpecas_redis
    restart: always

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: linkpecas_meilisearch
    restart: always
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-sua_chave_mestra_super_secreta}
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

  # ==========================================
  # EVOLUTION API - O MOTOR DO WHATSAPP
  # ==========================================
  evolution_api:
    image: atendai/evolution-api:v2.1.1
    container_name: linkpecas_evolution
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - AUTHENTICATE=true
      - AUTHENTICATION_API_KEY=Seleida50!
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@db:5432/linkpecas
      - REDIS_URI=redis://redis:6379/1 
      - WEBHOOK_GLOBAL_URL=https://api.linkpecas.online/api/webhooks/whatsapp
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_EVENTS=MESSAGES_UPSERT
    volumes:
      - ./evolution_instances:/evolution/instances
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: linkpecas_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h & wait $${!};
      done"

volumes:
  postgres_data:
  certbot_www:
  certbot_conf:
  meilisearch_data: